WebOdev/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebOdev.Models;

namespace WebOdev.Controllers
{
    public class KategoriController : Controller
    {
        private readonly KitapDBContext _context;
        public KategoriController(KitapDBContext kitap)
        {
            _context = kitap;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult KategoriSil(Kategori kategori)
        {
            var kategoriGetir = _context.Kategoris.Find(kategori.KategoriId);
            try
            {
                _context.Kategoris.Remove(kategoriGetir);
                _context.SaveChanges();
            }
            catch(Exception e)
            {
                Redirect("/Hata/Yorum");
            }
            return Redirect("/Admin/Index");
        }
        public IActionResult KategoriGuncelle(Kategori kategori)
        {
            var kategoriGetir = _context.Kategoris.Find(kategori.KategoriId);
            kategoriGetir.KategoriAdi = kategori.KategoriAdi;
            _context.Update(kategoriGetir);
            _context.SaveChanges();
            return Redirect("/Admin/Index");
        }
        public IActionResult KategoriEkle(Kategori kategori)
        {
            _context.Kategoris.Add(kategori);
            _context.SaveChanges();
            return Redirect("/Admin/Index");
        }
    }
}

WebOdev/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebOdev.Models;

namespace WebOdev.Controllers
{
    public class KitapController : Controller
    {
        private readonly KitapDBContext _context;
        public KitapController(KitapDBContext kitap)
        {
            _context = kitap;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult KitapSil(Kitap kitap)
        {
            if(kitap == null)
            {
                return BadRequest();
            }
            var kitapGetir = _context.Kitaps.Find(kitap.KitapId);
            try
            {
                _context.Remove(kitapGetir);
                _context.SaveChanges();
            }
            catch(Exception e)
            {
                return NotFound();
            }
            return Redirect("/Admin/Index");
        }
        public IActionResult KitapGuncelle(Kitap kitap)
        {
            if (kitap == null)
            {
                return BadRequest();
            }
            var kitapGetir = _context.Kitaps.Find(kitap.KitapId);

            kitapGetir.KitapAdi = kitap.KitapAdi;
            kitapGetir.YazarId = kitap.YazarId;
            kitapGetir.KategoryId = kitap.KategoryId;
            kitapGetir.YorumId = kitap.YorumId;
            kitapGetir.ResimUrl = kitap.ResimUrl;
            kitapGetir.Puan = kitap.Puan;
            _context.Kitaps.Update(kitapGetir);
            _context.SaveChanges();

            return Redirect("/Admin/Index");

        }
        [HttpPost]
        public IActionResult KitapEkle(Kitap kitap)
        {
            try
            {
                _context.Kitaps.Add(kitap);
                _context.SaveChanges();
            }
            catch(Exception e)
            {
                return BadRequest();
            }
            return Redirect("/Admin/Index");
        }
    }
}

WebOdev/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebOdev.Models;

namespace WebOdev.Controllers
{
    public class YazarController : Controller
    {
        private readonly KitapDBContext _context;
        public YazarController(KitapDBContext kitap)
        {
            _context = kitap;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult YazarSil(Yazar yazar)
        {
            var yazarGetir = _context.Yazars.Find(yazar.YazarId);
            try
            {
                _context.Yazars.Remove(yazarGetir);
                _context.SaveChanges();
            }
            catch(Exception e)
            {
                return Redirect("/Hata/Yazar");
            }
            return Redirect("/Admin/Index");
        }
        [HttpPost]
        public IActionResult YazarGuncelle(Yazar yazar)
        {
            if(yazar.YazarId == 0)
            {
                return NotFound();
            }
            var yazarGetir = _context.Yazars.Find(yazar.YazarId);
            yazarGetir.YazarAdi = yazar.YazarAdi;
            yazarGetir.YazarSoyadi = yazar.YazarSoyadi;
            _context.Update(yazarGetir);
            _context.SaveChanges();
            return Redirect("/Admin/Index");
        }
        [HttpPost]
        public IActionResult YazarEkle(Yazar yazar)
        {
            _context.Yazars.Add(yazar);
            _context.SaveChanges();
            return Redirect("/Admin/Index");
        }
    }
}

WebOdev/Controllers/YorumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebOdev.Models;

namespace WebOdev.Controllers
{
    public class YorumController : Controller
    {
        private readonly KitapDBContext _context;
        public YorumController(KitapDBContext kitap)
        {
            _context = kitap;

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult YorumSil(Yorum yorum)
        {
            var yorumGetir = _context.Yorums.Find(yorum.YorumId);
            try
            {
                _context.Remove(yorumGetir);
                _context.SaveChanges();
            }
            catch(Exception e)
            {
                return Redirect("/Hata/Yorum");
            }
            return Redirect("/Anasayfa/Index");
        }
         [HttpPost]
        public IActionResult YorumGuncelle(Yorum yorum)
        {
            if(yorum.YorumId == 0)
            {
                return NotFound();
            }
            var yorumGetir = _context.Yorums.Find(yorum.YorumId);
            yorumGetir.Yorum1 = yorum.Yorum1;
            _context.Yorums.Update(yorumGetir);
            _context.SaveChanges();
            return Redirect("/Admin/Index");
        }
        [HttpPost]
        public IActionResult YorumEkle(Yorum yorum)
        {
            _context.Add(yorum);
            _context.SaveChanges();
            return Redirect("/Admin/Index");
        }
    }
}

WebOdev/Views/Admin/Ekle.cshtml
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Ekle</h1>

WebOdev/Views/Admin/Index.cshtml
@model KitapYazarYorumKategoriModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="d-flex justify-content-center">Kitaplar</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Kitap id</th>
            <th scope="col">Kitap Adi</th>
            <th scope="col">Yazar ID</th>
            <th scope="col">Kategory ID</th>
            <th scope="col">Yorum ID</th>
            <th scope="col">Resim Url</th>
            <th scope="col">puan</th>
            <th scope="col">İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kitap in Model.Kitaplar)
        {
            <tr>
                <td>@kitap.KitapId</td>
                <td>@kitap.KitapAdi</td>
                <td>@kitap.YazarId</td>
                <td>@kitap.KategoryId</td>
                <td>@kitap.YorumId</td>
                <td>@kitap.ResimUrl</td>
                <td>@kitap.Puan</td>
                <td>
                    <a href="/Admin/KitapSil/@kitap.KitapId" class="btn btn-danger">Sil</a>
                    <a href="/Admin/KitapGuncelle/@kitap.KitapId" class="btn btn-warning">Guncelle</a>
                </td>
            </tr>
        }
    </tbody>

</table>


<h1 class="d-flex justify-content-center">Kategori</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Kategori id</th>
            <th scope="col">Kategori Adi</th>
            <th scope="col">İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kategori in Model.Kategoriler)
        {
            <tr>
                <td>@kategori.KategoriId</td>
                <td>@kategori.KategoriAdi</td>
                <td>
                    <a href="/Admin/KategoriSil/@kategori.KategoriId" class="btn btn-danger">Sil</a>
                    <a href="/Admin/KategoriGuncelle/@kategori.KategoriId" class="btn btn-warning">Guncelle</a>
                </td>
            </tr>
        }
    </tbody>

</table>


<h1 class="d-flex justify-content-center">Yorumlar</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Yorum id</th>
            <th scope="col">Yorum Adi</th>
            <th scope="col">İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var yorum in Model.Yorumlar)
        {
            <tr>
                <td>@yorum.YorumId</td>
                <td>@yorum.Yorum1</td>
                <td>
                    <a href="/Admin/YorumSil/@yorum.YorumId" class="btn btn-danger">Sil</a>
                    <a href="/Admin/YorumGuncelle/@yorum.YorumId" class="btn btn-warning">Guncelle</a>
                </td>
            </tr>
        }
    </tbody>

</table>

<h1 class="d-flex justify-content-center">Yazar</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Yazar id</th>
            <th scope="col">Yazar Adı</th>
            <th scope="col">Yazar Soyadı</th>
            <th scope="col">İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var yazar in Model.Yazarlar)
        {
            <tr>
                <td>@yazar.YazarId</td>
                <td>@yazar.YazarAdi</td>
                <td>@yazar.YazarSoyadi</td>
                <td>
                    <a href="/Admin/YazarSil/@yazar.YazarId" class="btn btn-danger">Sil</a>
                    <a href="/Admin/YazarGuncelle/@yazar.YazarId" class="btn btn-warning">Guncelle</a>
                </td>
            </tr>

        }

    </tbody>

</table>

WebOdev/Views/Admin/KategoriEkle.cshtml
@model Kategori
@{
    ViewData["Title"] = "KategoriEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>KategoriEkle</h1>

<form asp-action="KategoriEkle" asp-controller="Kategori" method="post">
    <label>Kategori Adı:</label>
    <input type="text" class="form-control my-2" asp-for="KategoriAdi" />
    <button type="submit" class="btn btn-outline-success btn-block">Ekle</button>
</form>

WebOdev/Views/Admin/KategoriSil.cshtml
@model Kategori
@{
    ViewData["Title"] = "KategoriSil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yaptığınız İşlemi Geri Alamazsınız</h1>
<form asp-action="KategoriSil" asp-controller="Kategori" method="post">
    <input type="text" class="form-control my-2" asp-for="KategoriId"  />
    <input type="text" class="form-control my-2" asp-for="KategoriAdi" />
    <button type="submit" class="btn btn-outline-danger btn-block">Sil</button>
</form>

   

WebOdev/Views/Admin/KitapEkle.cshtml
@model Kitap
@{
    ViewData["Title"] = "KitapEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>KitapEkle</h1>

<form asp-controller="Kitap" asp-action="KitapEkle" method="post">
    <label>Kitap Adı</label>
    <input type="text" class="form-control my-2"  asp-for="KitapAdi" />
    <label>Yazar ID</label>
    <input type="text" class="form-control my-2"  asp-for="YazarId" />
    <label>Kategori ID</label>
    <input type="text" class="form-control my-2"  asp-for="KategoryId" />
    <label>Yorum ID</label>
    <input type="text" class="form-control my-2"  asp-for="YorumId" />
    <label>Resim URL</label>
    <input type="text" class="form-control my-2"  asp-for="ResimUrl" />
    <label>Puan</label>
    <input type="text" class="form-control my-2"  asp-for="Puan" />
    <button class="btn btn-outline-success btn-block">Ekle</button>
</form>

WebOdev/Views/Admin/KitapGuncelle.cshtml
@model Kitap
@{
    ViewData["Title"] = "KitapGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yaptığınız İşlemleri Geri Alamazsınız</h1>
<form asp-controller="Kitap" asp-action="KitapGuncelle" method="post">
    <label>Kitap ID</label>
    <input type="text" class="form-control my-2" readonly asp-for="KitapId" />
    <label>Kitap Adı</label>
    <input type="text" class="form-control my-2"  asp-for="KitapAdi" />
    <label>Yazar ID</label>
    <input type="text" class="form-control my-2"  asp-for="YazarId" />
    <label>Kategori ID</label>
    <input type="text" class="form-control my-2"  asp-for="KategoryId" />
    <label>Yorum ID</label>
    <input type="text" class="form-control my-2"  asp-for="YorumId" />
    <label>Resim URL</label>
    <input type="text" class="form-control my-2"  asp-for="ResimUrl" />
    <label>Puan</label>
    <input type="text" class="form-control my-2"  asp-for="Puan" />
    <button class="btn btn-outline-warning btn-block">Guncelle</button>
</form>

WebOdev/Views/Admin/KitapSil.cshtml
@model Kitap
@{
    ViewData["Title"] = "KitapSil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yaptığınız İşlemleri Geri Alamazsınız</h1>
<form asp-controller="Kitap" asp-action="KitapSil" method="post">
    <label>Kitap ID</label>
    <input type="text" class="form-control my-2" readonly asp-for="KitapId" />
    <label>Kitap Adı</label>
    <input type="text" class="form-control my-2" readonly asp-for="KitapAdi" />
    <label>Yazar ID</label>
    <input type="text" class="form-control my-2" readonly asp-for="YazarId" />
    <label>Kategori ID</label>
    <input type="text" class="form-control my-2" readonly asp-for="KategoryId" />
    <label>Yorum ID</label>
    <input type="text" class="form-control my-2" readonly asp-for="YorumId" />
    <label>Resim URL</label>
    <input type="text" class="form-control my-2" readonly asp-for="ResimUrl" />
    <label>Puan</label>
    <input type="text" class="form-control my-2" readonly asp-for="Puan" />
    <button class="btn btn-outline-danger btn-block">Sil</button>
</form>

    

WebOdev/Views/Admin/Sil.cshtml
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Sil</h1>

WebOdev/Views/Admin/YazarEkle.cshtml
@model Yazar
@{
    ViewData["Title"] = "YazarEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>YazarEkle</h1>

<form asp-controller="Yazar" asp-action="YazarEkle" method="post">
    <span>Yazar Adı: </span>
    <input type="text" class="form-control my-2" asp-for="YazarAdi" />
    <span>Yazar Soyad: </span>
    <input type="text" class="form-control my-2" asp-for="YazarSoyadi" />
    <button type="submit" class="btn btn-outline-success btn-block">Ekle</button>
</form>

WebOdev/Views/Admin/YazarGuncelle.cshtml
@model Yazar
@{
    ViewData["Title"] = "YazarGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<h1>YazarGuncelle</h1>

<form asp-controller="Yazar" asp-action="YazarGuncelle" method="post">

        <span>Yazar ID: </span>
        <input type="text" class="form-control my-2"  asp-for="YazarId" readonly/>
        <span>Yazar Adı: </span>
        <input type="text" class="form-control my-2" asp-for="YazarAdi"  />
        <span>Yazar Adı: </span>
        <input type="text" class="form-control my-2" asp-for="YazarSoyadi"  />
    

    <button type="submit" class="btn btn-outline-danger btn-block">Guncelle</button>

</form>

WebOdev/Views/Admin/YazarSil.cshtml
@model Yazar
@{
    ViewData["Title"] = "YazarSil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>YazarSil</h1>
<form asp-action="YazarSil" asp-controller="Yazar" method="post">
    <span>Yazar ID: </span><input type="text" class="form-control my-2" readonly asp-for="YazarId" />
    <span>Yazar Adı: </span><input type="text" class="form-control my-2" readonly asp-for="YazarAdi" />
    <span>Yazar Adı: </span><input type="text" class="form-control my-2" readonly asp-for="YazarSoyadi" />
    <button type="submit"  class="btn btn-outline-danger btn-block">Sil</button>
</form>
        
    

WebOdev/Views/Admin/YorumEkle.cshtml
@model Yorum
@{
    ViewData["Title"] = "YorumEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>YorumEkle</h1>
<form asp-action="YorumEkle" asp-controller="Yorum" method="post">
    <textarea type="text" cols="50" rows="4" class="form-control my-2" asp-for="Yorum1"></textarea>
    <button type="submit" class="btn btn-outline-success btn-block">Ekle</button>

</form>

WebOdev/Views/Admin/YorumGuncelle.cshtml
@model Yorum
@{
    ViewData["Title"] = "YorumGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yorum Guncelle</h1>

<form asp-action="YorumGuncelle" asp-controller="Yorum" method="post">
    <input type="text" class="form-control my-2" asp-for="YorumId" readonly/>
    <textarea asp-for="Yorum1" cols="50" rows="3" class="form-control my-2"></textarea>
    <button class="btn btn-block btn-outline-warning">Guncelle</button>
</form>

WebOdev/Views/Admin/YorumSil.cshtml
@model Yorum
@{
    ViewData["Title"] = "YorumSil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>YorumSil</h1>
<form asp-action="YorumSil" asp-controller="Yorum" method="post">
    <input type="text" class="form-control my-2" value="YorumId" readonly />
    <textarea type="text" cols="50" rows="4" class="form-control my-2" asp-for="Yorum1"></textarea>
    <button type="submit" class="btn btn-outline-danger btn-block">Sil</button>

</form>
    